/**
 * The provider signs its commercial Protection Manifest, once, and the signed
 * artifact is committed. The seller key signs. The issuer key does not appear
 * here except as the permittedIssuer the manifest names.
 *
 * Run: npm run sign:manifest
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { accounts } from "../chain.js";
import { signManifest, type ManifestBody } from "../manifest.js";
import { PERMITTED_ISSUER } from "../fixtures/evidence.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "fixtures", "manifest.signed.ts");

/** Frozen. The end of the observation window, so nothing here moves with the clock. */
const ISSUED_AT = Math.floor(Date.parse("2026-08-22T01:51:22Z") / 1000);

const body: ManifestBody = {
  offerId: "protected-eth-usd-feed",
  vendor: "Recourse-compatible feed provider",
  endpoint: "/apis/v1/coingecko/coins/markets",
  priceMicrosUsd: "10000",
  claim: "every record generated within the last 60 seconds",
  subject: "RECORD",
  property: "GENERATION_TIME",
  thresholdSeconds: "60",
  permittedIssuer: PERMITTED_ISSUER as `0x${string}`,
  expectedSourceId: "COINBASE_ETH_USD_FEED",
  issuedAt: String(ISSUED_AT),
};

const signed = await signManifest(accounts.seller, body);

const file = `/**
 * GENERATED by agent/src/demo/sign-manifest.ts. Do not edit by hand.
 *
 * The provider's commercial Protection Manifest, signed by the SELLER key
 * (accounts.seller). The permittedIssuer named inside is a different key
 * (accounts.upstream), and it is that key whose delivery commitments the escrow
 * accepts. Seller signs what is promised; issuer signs what was observed.
 */
import type { SignedManifest } from "../manifest.js";

export const PROVIDER_MANIFEST: SignedManifest = ${JSON.stringify(signed, null, 2)} as SignedManifest;
`;

writeFileSync(OUT, file);
console.log(`signed by seller ${signed.signer}`);
console.log(`  permittedIssuer named inside: ${signed.manifest.permittedIssuer}`);
console.log(`  roles separate: ${signed.signer.toLowerCase() !== signed.manifest.permittedIssuer.toLowerCase()}`);
console.log(`  signature ${signed.signature.slice(0, 26)}...`);
console.log(`  written -> ${OUT}`);
