/**
 * GENERATED by agent/src/demo/sign-manifest.ts. Do not edit by hand.
 *
 * The provider's commercial Protection Manifest, signed by the SELLER key
 * (accounts.seller). The permittedIssuer named inside is a different key
 * (accounts.upstream), and it is that key whose delivery commitments the escrow
 * accepts. Seller signs what is promised; issuer signs what was observed.
 */
import type { SignedManifest } from "../manifest.js";

export const PROVIDER_MANIFEST: SignedManifest = {
  "manifest": {
    "offerId": "protected-eth-usd-feed",
    "vendor": "Recourse-compatible feed provider",
    "endpoint": "/apis/v1/coingecko/coins/markets",
    "priceMicrosUsd": "10000",
    "claim": "every record generated within the last 60 seconds",
    "subject": "RECORD",
    "property": "GENERATION_TIME",
    "thresholdSeconds": "60",
    "permittedIssuer": "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
    "expectedSourceId": "COINBASE_ETH_USD_FEED",
    "issuedAt": "1787363482"
  },
  "signer": "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
  "signature": "0x4f1f66d1287d083e7970f3d9c75ad5553c22194088719639f81b1689877bff523bb1512723dc4df511d1dab2f19ead318b7fe6a33e85aa30683a86ccbb516a651c",
  "domain": {
    "name": "Recourse Protection Manifest",
    "version": "1"
  },
  "primaryType": "ProtectionManifest"
} as SignedManifest;
